---
database_host: localhost
database_port: 5432
database_ssl_mode: disable
database_ssl_ca: None

foreman_database_name: foreman
foreman_database_user: foreman
foreman_database_password: CHANGEME
candlepin_database_name: candlepin
candlepin_database_user: candlepin
candlepin_database_password: CHANGEME
pulp_database_name: pulp
pulp_database_user: pulp
pulp_database_password: CHANGEME
iop_remediations_database_name: remediations_db
iop_remediations_database_user: remediations_user
iop_remediations_database_password: CHANGEME
iop_advisor_database_name: advisor_db
iop_advisor_database_user: advisor_user
iop_advisor_database_password: CHANGEME
iop_vulnerability_database_name: vulnerability_db
iop_vulnerability_database_user: vulnerability_admin
iop_vulnerability_database_password: CHANGEME
iop_vmaas_database_name: vmaas_db
iop_vmaas_database_user: vmaas_admin
iop_vmaas_database_password: CHANGEME
iop_inventory_database_name: inventory_db
iop_inventory_database_user: inventory_admin
iop_inventory_database_password: CHANGEME

candlepin_database_host: "{{ database_host }}"
candlepin_database_port: "{{ database_port }}"
candlepin_database_ssl_mode: "{{ database_ssl_mode }}"
candlepin_database_ssl_ca: "{{ database_ssl_ca }}"

pulp_database_host: "{{ database_host }}"
pulp_database_port: "{{ database_port }}"
pulp_database_ssl_mode: "{{ database_ssl_mode }}"
pulp_database_ssl_ca: "{{ database_ssl_ca }}"

foreman_database_host: "{{ database_host }}"
foreman_database_port: "{{ database_port }}"
foreman_database_sslmode: "{{ database_ssl_mode }}"
foreman_database_sslrootcert: "{{ database_ssl_ca }}"

iop_remediations_database_host: "host.containers.internal"
iop_remediations_database_port: "{{ database_port }}"
iop_remediations_database_ssl_mode: "{{ database_ssl_mode }}"
iop_remediations_database_ssl_ca: "{{ database_ssl_ca }}"

iop_advisor_database_host: "host.containers.internal"
iop_advisor_database_port: "{{ database_port }}"
iop_advisor_database_ssl_mode: "{{ database_ssl_mode }}"
iop_advisor_database_ssl_ca: "{{ database_ssl_ca }}"

iop_vulnerability_database_host: "host.containers.internal"
iop_vulnerability_database_port: "{{ database_port }}"
iop_vulnerability_database_ssl_mode: "{{ database_ssl_mode }}"
iop_vulnerability_database_ssl_ca: "{{ database_ssl_ca }}"

iop_vmaas_database_host: "host.containers.internal"
iop_vmaas_database_port: "{{ database_port }}"
iop_vmaas_database_ssl_mode: "{{ database_ssl_mode }}"
iop_vmaas_database_ssl_ca: "{{ database_ssl_ca }}"

iop_inventory_database_host: "host.containers.internal"
iop_inventory_database_port: "{{ database_port }}"
iop_inventory_database_ssl_mode: "{{ database_ssl_mode }}"
iop_inventory_database_ssl_ca: "{{ database_ssl_ca }}"

postgresql_databases:
  - name: "{{ candlepin_database_name }}"
    owner: "{{ candlepin_database_user }}"
  - name: "{{ foreman_database_name }}"
    owner: "{{ foreman_database_user }}"
  - name: "{{ pulp_database_name }}"
    owner: "{{ pulp_database_user }}"
  - name: "{{ iop_remediations_database_name }}"
    owner: "{{ iop_remediations_database_user }}"
  - name: "{{ iop_advisor_database_name }}"
    owner: "{{ iop_advisor_database_user }}"
  - name: "{{ iop_vulnerability_database_name }}"
    owner: "{{ iop_vulnerability_database_user }}"
  - name: "{{ iop_vmaas_database_name }}"
    owner: "{{ iop_vmaas_database_user }}"
  - name: "{{ iop_inventory_database_name }}"
    owner: "{{ iop_inventory_database_user }}"
postgresql_users:
  - name: "{{ candlepin_database_user }}"
    password: "{{ candlepin_database_password }}"
  - name: "{{ foreman_database_user }}"
    password: "{{ foreman_database_password }}"
  - name: "{{ pulp_database_user }}"
    password: "{{ pulp_database_password }}"
  - name: "{{ iop_remediations_database_user }}"
    password: "{{ iop_remediations_database_password }}"
  - name: "{{ iop_advisor_database_user }}"
    password: "{{ iop_advisor_database_password }}"
  - name: "{{ iop_vulnerability_database_user }}"
    password: "{{ iop_vulnerability_database_password }}"
  - name: "{{ iop_vmaas_database_user }}"
    password: "{{ iop_vmaas_database_password }}"
  - name: "{{ iop_inventory_database_user }}"
    password: "{{ iop_inventory_database_password }}"
