---
- name: Pull VMAAS container image
  containers.podman.podman_image:
    name: "{{ iop_vmaas_container_image }}:{{ iop_vmaas_container_tag }}"
    state: present

- name: Create VMAAS data volume
  containers.podman.podman_volume:
    name: iop-service-vmaas-data
    state: present

- name: Create podman secret for vmaas database username
  containers.podman.podman_secret:
    name: iop-service-vmaas-reposcan-database-username
    data: "{{ iop_vmaas_database_user }}"
  notify: restart vmaas

- name: Create podman secret for vmaas database password
  containers.podman.podman_secret:
    name: iop-service-vmaas-reposcan-database-password
    data: "{{ iop_vmaas_database_password }}"
  notify: restart vmaas

- name: Create podman secret for vmaas database name
  containers.podman.podman_secret:
    name: iop-service-vmaas-reposcan-database-name
    data: "{{ iop_vmaas_database_name }}"
  notify: restart vmaas

- name: Create podman secret for vmaas database host
  containers.podman.podman_secret:
    name: iop-service-vmaas-reposcan-database-host
    data: "{{ iop_vmaas_database_host }}"
  notify: restart vmaas

- name: Create podman secret for vmaas database port
  containers.podman.podman_secret:
    name: iop-service-vmaas-reposcan-database-port
    data: "{{ iop_vmaas_database_port }}"
  notify: restart vmaas

- name: Deploy VMAAS Reposcan Service
  containers.podman.podman_container:
    name: iop-service-vmaas-reposcan
    image: "{{ iop_vmaas_container_image }}:{{ iop_vmaas_container_tag }}"
    state: quadlet
    command: /vmaas/entrypoint.sh database-upgrade reposcan
    volume:
      - "iop-service-vmaas-data:/data"
    env:
      PORT: "8000"
      PROMETHEUS_PORT: "9000"
      PROMETHEUS_MULTIPROC_DIR: "/tmp/prometheus_multiproc_dir"
      SYNC_REPO_LIST_SOURCE: "katello"
      SYNC_REPOS: "yes"
      SYNC_CVE_MAP: "yes"
      SYNC_CVE: "yes"
      SYNC_OVAL: "yes"
      SYNC_CPE: "no"
      SYNC_CSAF: "no"
      SYNC_RELEASES: "no"
      SYNC_RELEASE_GRAPH: "no"
      KATELLO_URL: "http://host.containers.internal:24443"
      REDHAT_CVEMAP_URL: "http://host.containers.internal:24443/pub/iop/data/meta/v1/cvemap.xml"
      POSTGRESQL_SSL_MODE: "disable"
    secrets:
      - 'iop-service-vmaas-reposcan-database-username,type=env,target=POSTGRESQL_USER'
      - 'iop-service-vmaas-reposcan-database-password,type=env,target=POSTGRESQL_PASSWORD'
      - 'iop-service-vmaas-reposcan-database-name,type=env,target=POSTGRESQL_DATABASE'
      - 'iop-service-vmaas-reposcan-database-host,type=env,target=POSTGRESQL_HOST'
      - 'iop-service-vmaas-reposcan-database-port,type=env,target=POSTGRESQL_PORT'
    quadlet_options:
      - |
        [Unit]
        Description=VMAAS Reposcan Service
        [Service]
        Restart=on-failure
        [Install]
        WantedBy=default.target

- name: Deploy VMAAS Webapp-Go Service
  containers.podman.podman_container:
    name: iop-service-vmaas-webapp-go
    image: "{{ iop_vmaas_container_image }}:{{ iop_vmaas_container_tag }}"
    state: quadlet
    command: /vmaas/entrypoint.sh webapp-go
    env:
      REPOSCAN_PUBLIC_URL: "http://iop-service-vmaas-reposcan:8000"
      REPOSCAN_PRIVATE_URL: "http://iop-service-vmaas-reposcan:10000"
      CSAF_UNFIXED_EVAL_ENABLED: "FALSE"
      GIN_MODE: "release"
      POSTGRESQL_SSL_MODE: "disable"
      PORT: "8000"
    secrets:
      - 'iop-service-vmaas-reposcan-database-username,type=env,target=POSTGRESQL_USER'
      - 'iop-service-vmaas-reposcan-database-password,type=env,target=POSTGRESQL_PASSWORD'
      - 'iop-service-vmaas-reposcan-database-name,type=env,target=POSTGRESQL_DATABASE'
      - 'iop-service-vmaas-reposcan-database-host,type=env,target=POSTGRESQL_HOST'
      - 'iop-service-vmaas-reposcan-database-port,type=env,target=POSTGRESQL_PORT'
    quadlet_options:
      - |
        [Unit]
        Description=VMAAS Webapp-Go Service
        Wants=iop-service-vmaas-reposcan.service
        After=iop-service-vmaas-reposcan.service
        [Service]
        Restart=on-failure
        [Install]
        WantedBy=default.target

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start VMAAS Reposcan service
  ansible.builtin.systemd:
    name: iop-service-vmaas-reposcan
    enabled: true
    state: started

- name: Start VMAAS Webapp-Go service
  ansible.builtin.systemd:
    name: iop-service-vmaas-webapp-go
    enabled: true
    state: started