---
- name: Extract the DN from the client certificate
  ansible.builtin.command: "openssl x509 -in {{ candlepin_client_certificate }} -noout -subject -nameopt rfc2253,sep_comma_plus_space"
  register: openssl_response

- name: Set candlepin_artemis_client_dn
  ansible.builtin.set_fact:
    candlepin_artemis_client_dn: "{{ openssl_response.stdout | replace('subject=', '') }}"

- name: Create Candlepin broker.xml
  containers.podman.podman_secret:
    state: present
    name: broker.xml
    data: "{{ lookup('ansible.builtin.template', 'broker.xml.j2') }}"

- name: Create Tomcat login config
  containers.podman.podman_secret:
    state: present
    name: login.config
    data: "{{ lookup('ansible.builtin.template', 'login.config') }}"

- name: Create Tomcat jaas.conf
  containers.podman.podman_secret:
    state: present
    name: jaas.conf
    data: "{{ lookup('ansible.builtin.template', 'jaas.conf') }}"

- name: Create Tomcat cert-roles.properties
  containers.podman.podman_secret:
    state: present
    name: cert-roles.properties
    data: "{{ lookup('ansible.builtin.template', 'cert-roles.properties') }}"

- name: Create Tomcat cert-users.properties
  containers.podman.podman_secret:
    state: present
    name: cert-users.properties
    data: "{{ lookup('ansible.builtin.template', 'cert-users.properties.j2') }}"
