---
- name: Deploy Candlepin quadlet
  containers.podman.podman_container:
    name: "candlepin"
    image: "{{ candlepin_container_image }}:{{ candlepin_container_tag }}"
    state: quadlet
    network: host
    hostname: "{{ ansible_fqdn }}"
    secrets:
      - 'candlepin-ca-cert,target=/etc/candlepin/certs/candlepin-ca.crt,mode=0440,type=mount'
      - 'candlepin-ca-key,target=/etc/candlepin/certs/candlepin-ca.key,mode=0440,type=mount'
      - 'candlepin-tomcat-keystore,target=/etc/candlepin/certs/keystore,mode=0440,type=mount'
      - 'candlepin-tomcat-truststore,target=/etc/candlepin/certs/truststore,mode=0440,type=mount'
    volumes:
      - /etc/tomcat/server.xml:/etc/tomcat/server.xml:Z
      - /etc/tomcat/tomcat.conf:/etc/tomcat/tomcat.conf:Z
      - /etc/tomcat/login.config:/etc/tomcat/login.config:Z
      - /etc/tomcat/cert-roles.properties:/etc/tomcat/cert-roles.properties:Z
      - /etc/tomcat/cert-users.properties:/etc/tomcat/cert-users.properties:Z
      - /etc/tomcat/conf.d/jaas.conf:/etc/tomcat/conf.d/jaas.conf:Z
      - /etc/candlepin/candlepin.conf:/etc/candlepin/candlepin.conf:Z
      - /etc/candlepin/broker.xml:/etc/candlepin/broker.xml:Z
      - /var/log/candlepin:/var/log/candlepin:Z
      - /var/log/tomcat:/var/log/tomcat:Z

- name: Create Tomcat user
  ansible.builtin.user:
    name: tomcat

- name: Candlepin configuration
  block:
  - name: Create the Candlepin config directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: '0755'
    loop:
    - /etc/candlepin
    - /var/log/candlepin

  - name: Copy Candlepin configuration
    ansible.builtin.template:
      src: candlepin.conf.j2
      dest: /etc/candlepin/candlepin.conf
      owner: root
      group: tomcat
      mode: '0640'

- ansible.builtin.include_tasks:
    file: certs.yml

- name: Tomcat configuration
  block:
  - name: Create the Tomcat config directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: tomcat
      mode: '0755'
    loop:
    - /etc/tomcat
    - /etc/tomcat/conf.d
    - /var/log/tomcat

  - name: Copy Tomcat server config
    ansible.builtin.template:
      src: server.xml.j2
      dest: /etc/tomcat/server.xml
      owner: root
      group: tomcat
      mode: '0640'

  - name: Copy Tomcat server config
    ansible.builtin.template:
      src: tomcat.conf
      dest: /etc/tomcat/tomcat.conf
      owner: root
      group: tomcat
      mode: '0640'

- name: Setup artemis
  ansible.builtin.include_tasks:
    file: artemis.yml

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start the Quadlet Demo Service
  ansible.builtin.systemd:
    name: candlepin
    state: restarted
